"""Shared helpers for the release gate: evidence (attestations), limitations, bindings.

Standard library only. Used by release_check.py, limitations.py and package.py.

An *attestation* is a recorded fact about a release, either written by a script run
(kind "auto", for example a host check that executed a packaged binary) or by a person
(kind "manual"). Each one is bound to what it vouches for, so it stops counting the
moment that thing changes:

    "binary:<os>/<arch>"  the sha256 of that target's executable in dist/release-manifest.json
    "ui_assets"           the sha256 of the four embedded browser assets
    "commit"              a git commit; still valid while only release/attestations.json changed since
"""

import datetime
import hashlib
import json
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
UI_ASSETS = ("index.html", "app.css", "app.js", "state.js")
ALLOWED_AFTER_COMMIT = {"release/attestations.json"}  # recording evidence must not invalidate evidence
STATUSES = ("accepted", "open", "closed")
README_BEGIN = "<!-- limitations:begin (generated by scripts/limitations.py from release/limitations.json; do not edit) -->"
README_END = "<!-- limitations:end -->"


def release_dir():
    return ROOT / "release"


def dist_dir():
    return ROOT / "dist"


def load_json(path, default=None):
    path = pathlib.Path(path)
    if not path.is_file():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def now_iso():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---- git ---------------------------------------------------------------------------

def git(*args, check=True):
    p = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True)
    if check and p.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {p.stderr.strip()}")
    return p.stdout


def head_commit():
    return git("rev-parse", "HEAD").strip()


def github_raw_url(path):
    """A raw.githubusercontent.com URL for `path` at HEAD, pinned to the exact commit so it
    never goes stale. None if origin is not a github.com remote (for example a dev clone with
    no remote, or one hosted elsewhere) -- callers must handle that by omitting the section."""
    try:
        origin = git("remote", "get-url", "origin").strip()
    except RuntimeError:
        return None
    m = re.search(r"github\.com[:/]([^/]+)/(.+?)(?:\.git)?$", origin)
    if not m:
        return None
    owner, repo = m.group(1), m.group(2)
    return f"https://raw.githubusercontent.com/{owner}/{repo}/{head_commit()}/{path}"


def changed_since(commit):
    """Paths that differ from `commit`, including uncommitted and untracked (not ignored) files."""
    diff = git("diff", "--name-only", commit).split()
    untracked = git("ls-files", "--others", "--exclude-standard").split()
    return sorted(set(diff) | set(untracked))


# ---- bindings ----------------------------------------------------------------------

def manifest():
    return load_json(dist_dir() / "release-manifest.json")


def ui_assets_sha256():
    h = hashlib.sha256()
    base = ROOT / "internal/adapters/webui"
    for name in UI_ASSETS:
        h.update(name.encode() + b"\0" + (base / name).read_bytes() + b"\0")
    return h.hexdigest()


def current_binding(key):
    """The present value for a binding key, or None if it cannot be determined."""
    if key == "ui_assets":
        return ui_assets_sha256()
    if key == "commit":
        return head_commit()
    if key.startswith("binary:"):
        m = manifest()
        t = (m or {}).get("targets", {}).get(key.split(":", 1)[1])
        return t["binary_sha256"] if t else None
    raise ValueError(f"unknown binding {key!r}")


def current_bindings(keys):
    return {k: current_binding(k) for k in keys}


# ---- attestations ------------------------------------------------------------------

def attestations():
    return (load_json(release_dir() / "attestations.json", {"attestations": []}) or {"attestations": []})["attestations"]


def add_attestation(entry):
    path = release_dir() / "attestations.json"
    data = load_json(path, {"attestations": []}) or {"attestations": []}
    data["attestations"].append(entry)
    release_dir().mkdir(exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")


def make_attestation(item, kind, by, note, binds):
    return {"id": item, "kind": kind, "by": by, "at": now_iso(), "note": note, "binds": binds}


def attestation_problem(att):
    """None if the attestation still holds, else why it does not."""
    for key, recorded in att["binds"].items():
        if key == "commit":
            try:
                extra = [p for p in changed_since(recorded) if p not in ALLOWED_AFTER_COMMIT]
            except RuntimeError:
                return f"commit {recorded[:10]} is unknown to this repository"
            if extra:
                return f"changed since commit {recorded[:10]}: {', '.join(extra[:4])}{' ...' if len(extra) > 4 else ''}"
            continue
        try:
            now = current_binding(key)
        except (OSError, ValueError):
            now = None
        if now is None:
            return f"cannot read the current value of {key}"
        if now != recorded:
            return f"{key} changed since it was recorded ({recorded[:10]} -> {now[:10]})"
    return None


def latest_valid(item, atts=None):
    """(attestation, None) for the newest attestation of `item` that still holds, else (None, why not)."""
    mine = [a for a in (atts if atts is not None else attestations()) if a["id"] == item]
    if not mine:
        return None, "no attestation recorded"
    reason = None
    for a in reversed(mine):
        reason = attestation_problem(a)
        if reason is None:
            return a, None
    return None, f"latest attestation no longer holds: {reason}"


# ---- limitations -------------------------------------------------------------------

def limitations():
    return (load_json(release_dir() / "limitations.json", {"limitations": []}) or {"limitations": []})["limitations"]


def limitation_problems(items, atts=None):
    """(errors, warnings) about the limitations list and the evidence behind it."""
    errors, warnings, seen = [], [], set()
    atts = atts if atts is not None else attestations()
    for it in items:
        lid = it.get("id", "?")
        for field in ("id", "title", "text", "status"):
            if not it.get(field):
                errors.append(f"{lid}: missing {field}")
        if lid in seen:
            errors.append(f"{lid}: duplicate id")
        seen.add(lid)
        if it.get("status") not in STATUSES:
            errors.append(f"{lid}: status must be one of {STATUSES}")
        for ev in it.get("evidence", []):
            att, why = latest_valid(ev, atts)
            if att is None:
                errors.append(f"{lid}: its text relies on '{ev}' but {why}")
        closes = it.get("closes_with", [])
        valid = [latest_valid(c, atts)[0] is not None for c in closes]
        if it.get("status") == "closed":
            if not closes or not all(valid):
                errors.append(f"{lid}: marked closed without valid evidence ({', '.join(closes) or 'closes_with is empty'})")
        elif closes and all(valid):
            warnings.append(f"{lid}: evidence to close it exists ({', '.join(closes)}); set its status to closed and run scripts/limitations.py --write")
        if it.get("status") != "closed" and not it.get("closes_when"):
            errors.append(f"{lid}: needs closes_when (how it would be closed, or why it is accepted)")
    return errors, warnings


def render_readme_block(items):
    lines = [README_BEGIN, ""]
    for it in items:
        if it["status"] != "closed":
            lines.append(f"- **{it['title']}.** {it['text']}")
    lines += ["", "How each limit is tracked and closed: [docs/limitations.md](docs/limitations.md).", "", README_END]
    return "\n".join(lines)


def render_limitations_doc(items):
    out = ["# Known limitations", "",
           "This file is generated by `scripts/limitations.py` from `release/limitations.json`; edit that file, not this one.",
           "Each limitation is **accepted** (a stated limit that stays), **open** (a check or piece of evidence would close it) or",
           "**closed** (evidence recorded). A limitation can only assert facts that have valid evidence, and cannot be marked closed",
           "without it (`scripts/release_check.py`).", ""]
    for it in items:
        out += [f"## {it['title']}", "", f"Status: **{it['status']}** (`{it['id']}`)", "", it["text"], ""]
        if it.get("closes_when"):
            out += [f"How it closes: {it['closes_when']}", ""]
        if it.get("evidence"):
            out += ["Recorded evidence this text relies on: " + ", ".join(f"`{e}`" for e in it["evidence"]) + ".", ""]
    return "\n".join(out).rstrip() + "\n"


def readme_with_block(readme_text, block):
    b, e = readme_text.find(README_BEGIN), readme_text.find(README_END)
    if b < 0 or e < 0 or e < b:
        raise ValueError("README.md is missing the limitations markers")
    return readme_text[:b] + block + readme_text[e + len(README_END):]
