package ollama

import (
	"context"
	"encoding/json"
	"net/http"
	"strings"
	"testing"

	"taskworker.local/taskworker/internal/core"
)

func TestModelfileRendererGate(t *testing.T) {
	const base = "# generated by Ollama\nFROM C:\\models\\weights\nTEMPLATE {{ .Messages }}\n"
	for _, tc := range []struct {
		name, source, template string
		want                   bool
	}{
		{"ordinary", base, "{{ .Messages }}", true},
		{"no_final_newline", strings.TrimSuffix(base, "\n"), "{{ .Messages }}", true},
		{"crlf", strings.ReplaceAll(base, "\n", "\r\n"), "{{ .Messages }}", true},
		{"case_tabs", "from\t/local/path\ntemplate\t{{ .Messages }}\n", "{{ .Messages }}", true},
		{"renderer", base + "RENDERER qwen3.5\n", "{{ .Messages }}", false},
		{"renderer_lowercase", base + "\treNDerer \"qwen3.5\"\n", "{{ .Messages }}", false},
		{"renderer_empty", base + "RENDERER \"\"\n", "{{ .Messages }}", false},
		{"renderer_eof", base + "RENDERER qwen3.5", "{{ .Messages }}", false},
		{"comments", base + "# RENDERER qwen3.5\n  # RENDERER \"\"\"\n", "{{ .Messages }}", true},
		{"single_quoted_multiline", base + "SYSTEM \"first line\nRENDERER not a directive\nlast line\"\n", "{{ .Messages }}", true},
		{"triple_quoted_multiline", base + "SYSTEM \"\"\"first \"quoted\" line\nRENDERER not a directive\nlast line\"\"\"\n", "{{ .Messages }}", true},
		{"template_text", "FROM /local/path\nTEMPLATE \"\"\"{{ .Messages }}\nRENDERER content\"\"\"\n", "{{ .Messages }}\nRENDERER content", true},
		{"license_text", base + "LICENSE \"copyright\nRENDERER content\"\n", "{{ .Messages }}", true},
		{"parameter_text", base + "PARAMETER stop \"prefix\nRENDERER content\"\nPARAMETER stop \"\"\n", "{{ .Messages }}", true},
		{"raw_text", base + "SYSTEM renderer is a word, not a command\nPARSER qwen\nPARAMETER temperature 0.7\n", "{{ .Messages }}", true},
		{"directive_after_quotes", base + "SYSTEM \"first\nRENDERER content\"\nRENDERER qwen3.5\n", "{{ .Messages }}", false},
		{"missing", "", "{{ .Messages }}", false},
		{"comment_only", "# no evidence\n", "{{ .Messages }}", false},
		{"from_only", "FROM /local/path\n", "{{ .Messages }}", false},
		{"missing_from", "TEMPLATE {{ .Messages }}\n", "{{ .Messages }}", false},
		{"template_mismatch", base, "different", false},
		{"duplicate_template", base + "TEMPLATE {{ .Messages }}\n", "{{ .Messages }}", false},
		{"duplicate_from", base + "FROM /elsewhere\n", "{{ .Messages }}", false},
		{"unknown_directive", base + "UNKNOWN value\n", "{{ .Messages }}", false},
		{"missing_argument", base + "SYSTEM\n", "{{ .Messages }}", false},
		{"unterminated_single", base + "SYSTEM \"content\nRENDERER hidden\n", "{{ .Messages }}", false},
		{"unterminated_triple", base + "SYSTEM \"\"\"content\nRENDERER hidden\n", "{{ .Messages }}", false},
		{"quoted_trailing_garbage", base + "SYSTEM \"text\" garbage\n", "{{ .Messages }}", false},
		{"nested_delimiter", base + "SYSTEM \"\"\"before \"\"\" after\"\"\"\n", "{{ .Messages }}", false},
		{"backslash_is_not_escape", base + "SYSTEM \"text\\\" suffix\"\n", "{{ .Messages }}", false},
		{"stored_message", base + "MESSAGE user hidden\n", "{{ .Messages }}", false},
		{"nul", base + "SYSTEM nul\x00\n", "{{ .Messages }}", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			system := map[string]string{
				"single_quoted_multiline": "first line\nRENDERER not a directive\nlast line",
				"triple_quoted_multiline": "first \"quoted\" line\nRENDERER not a directive\nlast line",
				"raw_text":                "renderer is a word, not a command",
				"directive_after_quotes":  "first\nRENDERER content",
			}[tc.name]
			if got := templateOnlyModelfile(tc.source, tc.template, system); got != tc.want {
				t.Fatalf("got %v, want %v", got, tc.want)
			}
		})
	}
}

func TestShowModelfileCompatibilityAcrossBoundaries(t *testing.T) {
	for _, metadata := range []string{"renderer", "missing", "empty", "malformed", "mismatch", "quoted_text"} {
		for _, boundary := range []string{"discovery", "selection", "refresh"} {
			t.Run(metadata+"/"+boundary, func(t *testing.T) {
				f := defaults()
				original := f.show.(map[string]any)
				changed := map[string]any{}
				for k, v := range original {
					changed[k] = v
				}
				switch metadata {
				case "renderer":
					changed["modelfile"] = original["modelfile"].(string) + "RENDERER qwen3.5\nPARSER qwen3.5\n"
				case "missing":
					delete(changed, "modelfile")
				case "empty":
					changed["modelfile"] = ""
				case "malformed":
					changed["modelfile"] = original["modelfile"].(string) + "SYSTEM \"unterminated\n"
				case "mismatch":
					changed["modelfile"] = "FROM /local/path\nTEMPLATE another template\n"
				case "quoted_text":
					changed["modelfile"] = original["modelfile"].(string) + "SYSTEM \"\"\"quote \"text\"\nRENDERER ordinary text\"\"\"\n# RENDERER comment\n"
					changed["system"] = "quote \"text\"\nRENDERER ordinary text"
				}
				if boundary == "refresh" {
					f.hook = func(w http.ResponseWriter, r *http.Request) bool {
						if r.URL.Path != "/api/show" {
							return false
						}
						show := original
						if f.shows.Add(1) > 1 {
							show = changed
						}
						json.NewEncoder(w).Encode(show)
						return true
					}
				} else {
					f.show = changed
				}
				b, _ := f.server(t)
				want := metadata == "quoted_text"
				if boundary == "discovery" {
					models, err := b.Models(context.Background())
					if err != nil || len(models) != 1 || models[0].Capabilities.TextGeneration != want {
						t.Fatalf("discovery: %+v %v", models, err)
					}
					return
				}
				callbacks := 0
				_, err := b.Generate(context.Background(), input(), func(string) error { callbacks++; return nil })
				if want {
					if err != nil || callbacks != 2 {
						t.Fatalf("supported: %v callbacks=%d", err, callbacks)
					}
				} else {
					requireCode(t, err, core.ErrUnsupported)
					if callbacks != 0 {
						t.Fatal("unsupported input emitted")
					}
					f.mu.Lock()
					defer f.mu.Unlock()
					loads := 0
					if boundary == "refresh" {
						loads = 1
					}
					if len(f.requests) != loads {
						t.Fatalf("sent prompt or unexpected load: %+v", f.requests)
					}
				}
			})
		}
	}
}
